### PR TITLE
Arrays are always arrays

### PR DESCRIPTION
**Pull request by sbusch**
*So this one could be controversial, and is backwards-incompatible.*

Currently, when generator encounters an OpenAPI array definition, it generates

```code
   element: Array<type> | type
```

This PR removes the optional `| type`.

The reasoning for this could be (I haven't verified this) that the current generator lacks handling of [`oneOf`](https://json-schema.org/understanding-json-schema/reference/combining.html).

But - for my understanding - the PR represents the correct behavior. It also simplifies handling of array elements as we don't always have to handle two code paths in TS when there is just an array.

I don't know if anyone really needs the old, "fuzzy" behavior. If yes, there could be an option for this?

@mtennoe let me know what you think.

**Note**: this PR depends on PR #41

### CODE REVIEW

**Comment by sbusch** [comment]
This was the last one for today ;-)

**Comment by mtennoe** [comment]
Thanks for all the PRs! :)

I agree that this makes it cleaner and is the "right thing", but I am worried about backwards compatibility. However, it is possible to use custom schemas, so that alleviates the potential pain if this breaks something. We could also consider introducing a backwards compatible set of schemas for the code generation, which could also be used for easier and more gradual transitions in the future.

Want to give the "deprecated schemas" approach a shot?

**Comment by sbusch** [comment]
IMO this could become a mess in the future, when each backwards-breaking change lead to a new set of templates. People could even assume that the old template sets are still maintained, and submit issues for them (OK, this project is not too popular, but ... who knows).

So I prefer an approach using flags (e.g. `fuzzyArrays`). We could assume `true` as a default to retain backwards compatibility. Should be marked as deprecated. In some future, backwards-breaking version, it could then be toggled to `false` as default. More flags could be added in the future.

Everyone who needs an old template set for 100% backwards compatibility is already able to copy them from git history and use them as their templates with the [current implementation](https://github.com/mtennoe/swagger-typescript-codegen#custom-template).

**Comment by mtennoe** [comment]
Yup, that is definitely a concern with that approach (so it should probably be reduced to a n-X set of versions for backwards compatibility). Considering the size of this project though, its probably fine to remove this here. Its also fairly easy to convert to the new type.

**Comment by sbusch** [comment]
Don't know if I understand you correctly. Which variant should I implement (given that I find time for this), or is it ready to be merged as-is?

Btw, thanks for the merges + releases.

**Comment by mtennoe** [comment]
Ah yes, sorry, I was unclear. I mean the initial implementation is fine :)
Ill take another look at #41 tomorrow morning and merge and publish these two then

**Comment by mtennoe** [comment]
@sbusch - Looks like a conflict with #41

**Comment by mtennoe** [comment]
@sbusch 1.7.0 published

**Pull request merged**
